In [20]:
import numpy as np

In [21]:
a1 = np.array([1,2,3,4])

In [22]:
a1

array([1, 2, 3, 4])

In [23]:
a1.dtype

dtype('int32')

In [24]:
a1.shape

(4,)

In [25]:
a2 = np.array([5,6,7,8])

In [26]:
a2

array([5, 6, 7, 8])

In [27]:
a1*a2

array([ 5, 12, 21, 32])

In [28]:
a1+a2

array([ 6,  8, 10, 12])

In [ ]:
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
x = [1 for i in range(10)]
y = [i for i in range(10)]

In [ ]:
print(x,y)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
X = np.array(x).reshape((-1, 1))
Y = np.array(y).reshape((-1, 1))

In [ ]:
lin_regressor = LinearRegression()
lin_regressor.fit(X, Y)
Y_pred = lin_regressor.predict(X)

In [ ]:
alpha = str(round(lin_regressor.intercept_[0], 5))
beta = str(round(lin_regressor.coef_[0][0], 5))

In [ ]:
beta

In [ ]:
fig, ax = plt.subplots()

ax.set_title(f"Alpha {alpha}, Beta {beta}")
ax.scatter(X, Y)
ax.plot(X, Y_pred, c='r')
